server :
  port : 8080

springdoc:
  paths-to-match:
    - /**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location : classpath:mybatis-config.xml

spring:
  resources:
    static-path-pattern: /**

  mvc:
    static-path-pattern: /assets/**

  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://pingulion.shop/travel
    username : leejaehyeong
    password : lee6252

  jpa:
    hibernate:
      ddl-auto: none #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 663030448453-eh6fem840d9ap64j41ljnl8pip707goa.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          naver:
            client-id: QDtevbGhxq7CXh065YhE
            client-secret: qHWt4ERKtC
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


travel:
  api:
    key: "abrXZqSKB5RN73E%2Bz6r0fR5RIAVvZ7PzboQZM3bBaz4lCyEJpKHFgPC23uZwV1FmxdKE9s%2Borm90FSmqbS4ghA%3D%3D"

cloudflare:
  api:
    url: "https://api.cloudflare.com/client/v4/accounts/af4e045aec566b1f645ae7b3557552f7/images/v1"
    token: "KpDEuHiEPq1WG6xxIyvepTXlA6-Jsy7XngMtW4hD"
    accountHash: "ftV1RpijrL892iGuP8Q6zQ"

jwt:
  secret: f9bf63696be834db3cc418e1e1f1e7d089226c5fa05724d24c352f9f162d7cc1

#Email 인증
mail:
  host: smtp.gmail.com
  port: 587
  username: parkjuncheol77@gmail.com
  password: frrd wika tewd vcqf
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?

logging:
  level:
    com.example.travel_backend.jwt: DEBUG
    root: INFO